apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: jx-demo
version: 0.0.11
sources:
- https://github.com/snahider/jx-demo
maintainers:
- name: Angel Nu√±ez
  email: snahider@gmail.com